name: influencer

channels:
    - pytorch
    - nvidia
    - pyg
    - conda-forge

dependencies:
    - pytorch
    - pytorch-cuda==11.7
    - pyg
    - pip
    - pip:
        - -r file:requirements.txt