artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
input_dir: /global/cfs/cdirs/m3443/data/TrackLRP/attention_cut_dir_1
project: LRP_Study_D
model: GraphLevelAGNN
gpus: [2]
nodes: 1

# Dataset parameters
datatype_split: [20000, 100, 10] # Number of [training, validation, testing] examples
batch_size: 200
num_tracks: 10
num_layer: 10
detector_width: 0.5
cut_policy: 1.0
ptcut: 0.0
attention_cut: 0.2

# Model parameters
edge_cut: 0.5
spatial_channels: 2
hidden: 32
n_graph_iters: 6
nb_node_layer: 3
nb_edge_layer: 3
layernorm: True
batchnorm: False
aggregation: mean_sum
hidden_activation: SiLU
weight: 1.0
warmup: 20
lr: 0.0002
factor: 0.8
patience: 30
truth_key: y_trigger
max_epochs: 200

# GravNet-specific parameters
emb_dims: 8
knn: 100

cell_channels: 0