artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: LRP_Study_E
model: GravNet
gpus: 1
nodes: 1

# Dataset parameters
datatype_split: [20000, 1000, 10] # Number of [training, validation, testing] examples
batch_size: 200
num_tracks: 10
num_layer: 10
detector_width: 0.5
cut_policy: 1
ptcut: 0.0

# Model parameters
edge_cut: 0.5
spatial_channels: 2
hidden: 32
n_graph_iters: 2
nb_node_layer: 3
nb_edge_layer: 3
layernorm: False
batchnorm: True
aggregation: mean_sum
hidden_activation: SiLU
output_activation: 
weight: 1.0
warmup: 20
lr: 0.0002
factor: 0.8
patience: 40
scheduler:  
truth_key: y_trigger
max_epochs: 200

# GravNet-specific parameters
knn: 2 # If knn_start_end not set, then the number of neighbors in each GravNet conv
rand_k: 0

r: 
max_knn: 20

emb_dims: 16
grav_weight: 1.0
grav_level: 1 # 
norm: False

learned_grav_weight: False
grav_activation: 

cell_channels: 0