artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: Influencer_Experiment_B
model: InfluencerEmbedding

# Dataset parameters
datatype_split: [100, 10, 10] # Number of [training, validation, testing] examples
num_tracks: 3
track_dis_width: 0
num_layer: 10
min_r: 0.5
max_r: 2.0
detector_width: 0.5
ptcut: 0.0
nhits: 1

# Model parameters
spatial_channels: 2
emb_hidden: 512
emb_dim: 12
nb_layer: 4
activation: Tanh

knn: 50
radius: 0.1
margin: 0.1
randomisation: 1
points_per_batch: 100000

user_user_weight: 1
user_influencer_weight: 1
influencer_influencer_weight: 1
influencer_spread: [20, 5, 1]
influencer_exponent: 1
warmup: 10
lr: 0.001
factor: 0.8
patience: 10
regime: [rp, hnm, norm]
max_epochs: 10