artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: Influencer_Experiment_B
model: InfluencerEmbedding

# Dataset parameters
data_split: [10000, 1000, 1000] # Number of [training, validation, testing] examples
batch_size: 1000
num_tracks: 10
track_dis_width: 0
num_layer: 10
min_r: 0.5
max_r: 2.0
detector_width: 0.5
ptcut: 0.0
nhits: 1

# Model parameters
spatial_channels: 2
emb_hidden: 128
emb_dim: 12
nb_layer: 3

steps: 5
activation: SiLU
aggregation: [sum, mean, max, std]
concat_output: True
max_knn: 50
grav_weight: 3.0
r_train: 0.1
norm_hidden: True 
norm_embedding: True 
self_loop: False
emb_knn: 10

knn: 50
# radius: 1.0
radius: 0.1
# margin: 1.0
margin: 0.1
# influencer_margin: 3.0
influencer_margin: 0.3
randomisation: 1
points_per_batch: 100000

user_user_weight: 0.
user_user_pos_ratio: 1.0
user_influencer_weight: 0.3
user_influencer_pos_ratio: 1.0
influencer_influencer_weight: [1.0, 2.0, 2.0]
influencer_spread: 1
influencer_exponent: 1
user_user_loss_ratio: False
warmup: 10
lr: 0.002
factor: 0.8
patience: 20
regime: [rp, hnm, norm, radius]
max_epochs: 30